# Generated by Django 3.1.7 on 2021-04-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='eduxa_category',
        ),
    ]
